// Static copy of the archive — used only when the backend API is unreachable
// (e.g., a frontend-only static deploy). The live API remains the source of truth.
export const PROJECTS_FALLBACK = [
  {
    slug: "proddatur-dussehra",
    title: "Proddatur Dussehra",
    telugu: "ప్రొద్దుటూరు దసరా",
    type: "documentary",
    status: "completed",
    categories: ["Devotional", "Cultural"],
    location: "Proddatur",
    district: "Kadapa",
    state: "Andhra Pradesh",
    country: "India",
    year: "2025",
    duration: "Documentary",
    logline: "A town that burns its devotion into the night sky.",
    synopsis: "Every year, Proddatur transforms. Streets become rivers of flame and faith as one of Rayalaseema's most spectacular Dussehra celebrations unfolds — processions, rituals, and a community that carries its devotion quite literally on its shoulders. This documentary follows the festival from its quiet first lamps to its thunderous final night.",
    story: "Dussehra in Proddatur is not watched — it is lived. The film moves through ten days of preparation and release: the artisans who build the idols, the families who keep century-old vows, the drummers whose rhythms decide the pace of entire streets. What emerges is not a record of a festival, but a portrait of a town that measures its year in devotion.",
    place: "Proddatur, in the Kadapa district of Rayalaseema, sits on the banks of the Penna river — a trading town whose lanes hold temples, mosques and churches within walking distance of each other. During Dussehra, its identity condenses into a single, blazing civic ritual.",
    people: "Idol makers, temple priests, percussion troupes, municipal workers, grandmothers who have never missed a procession in sixty years — the film belongs to them.",
    hero: "/assets/projects/proddatur-hero.jpg",
    poster: "/assets/projects/proddatur-hero.jpg",
    gallery: ["/assets/projects/proddatur-2.jpg", "/assets/projects/proddatur-3.jpg", "/assets/projects/hero.jpg"],
    credits: [
      { role: "Direction & Production", name: "Balcony Originals" },
      { role: "Cinematography", name: "Balcony Originals Crew" },
      { role: "Sound & Edit", name: "Balcony Originals Post" },
    ],
    featured: true,
    order: 1,
  },
  {
    slug: "medaram-jatara",
    title: "Medaram Jatara",
    telugu: "మేడారం జాతర",
    type: "documentary",
    status: "completed",
    categories: ["Devotional", "Cultural", "People"],
    location: "Medaram",
    district: "Mulugu",
    state: "Telangana",
    country: "India",
    year: "2024",
    duration: "Documentary",
    logline: "Asia's largest tribal gathering, seen from the inside.",
    synopsis: "Once every two years, a small forest hamlet in Telangana becomes one of the largest human gatherings on earth. The Sammakka Saralamma Jatara draws millions of devotees into the Medaram forest — no temple, no idol house, just faith under the trees. This documentary walks with the pilgrims.",
    story: "There is no priesthood at the centre of Medaram — only memory. The film follows Koya tribal families, first-time visitors, and the unseen machinery of a state that must build a temporary city for millions in the middle of a forest. It asks what keeps a four-hundred-year-old act of remembrance alive.",
    place: "Medaram sits deep in the forests of Mulugu, Telangana. For most of the year it is silent. During the Jatara, the forest itself becomes the shrine.",
    people: "Koya elders, women carrying jaggery offerings equal to their body weight, volunteer doctors, tribal singers keeping oral histories — the gathering is the protagonist.",
    hero: "/assets/projects/medaram-hero.jpg",
    poster: "/assets/projects/medaram-hero.jpg",
    gallery: ["/assets/projects/medaram-2.jpg", "/assets/projects/medaram-3.jpg", "/assets/projects/hero.jpg"],
    credits: [
      { role: "Direction & Production", name: "Balcony Originals" },
      { role: "Cinematography", name: "Balcony Originals Crew" },
      { role: "Sound & Edit", name: "Balcony Originals Post" },
    ],
    featured: true,
    order: 2,
  },
  {
    slug: "yaganti",
    title: "Yaganti",
    telugu: "యాగంటి",
    type: "documentary",
    status: "upcoming",
    categories: ["Devotional", "Heritage"],
    location: "Yaganti",
    district: "Nandyala",
    state: "Andhra Pradesh",
    country: "India",
    year: "2026",
    duration: "Documentary",
    logline: "The stone Nandi that is still growing — and the people who believe it.",
    synopsis: "In the rocky folds of Nandyala district stands the Yaganti temple, home to a monolithic Nandi that devotees say grows a little every year. Between geology and faith, between cave shrines and prophecy, this upcoming documentary explores a place where stone is alive with story.",
    story: "Sage Agastya's penance, the crow that became a hill, the Nandi that outgrows its pillars — Yaganti is layered with legend. The film will trace how a single temple holds together geology, devotion and an entire region's imagination.",
    place: "Yaganti, set among the Erramala hills of Nandyala district, is one of Rayalaseema's most ancient sacred geographies — cave temples, natural springs and boulder hills that look sculpted by intent.",
    people: "Temple priests, historians, geologists, and the farming communities for whom Yaganti is not a destination but a neighbour.",
    hero: "/assets/projects/yaganti-hero.jpg",
    poster: "/assets/projects/yaganti-hero.jpg",
    gallery: ["/assets/projects/yaganti-2.jpg", "/assets/projects/roots.jpg"],
    credits: [{ role: "Direction & Production", name: "Balcony Originals" }],
    featured: true,
    order: 3,
  },
  {
    slug: "ahobilam",
    title: "Ahobilam",
    telugu: "అహోబిలం",
    type: "documentary",
    status: "upcoming",
    categories: ["Devotional", "Heritage"],
    location: "Ahobilam",
    district: "Nandyala",
    state: "Andhra Pradesh",
    country: "India",
    year: "2026",
    duration: "Documentary",
    logline: "Nine shrines hidden in a forest where the Lord is said to have torn a pillar apart.",
    synopsis: "Deep in the Nallamala forest, across gorges and stone steps, lie the nine Narasimha shrines of Ahobilam. This upcoming documentary is a pilgrimage on foot — through the upper and lower kshetras, following the devotees who still climb these hills the old way.",
    story: "Ahobilam is where myth has a mailing address. The film will walk the full circuit of the Nava Narasimha temples, listening to the legends of Hiranyakashipu and Prahlada in the very landscape where they are believed to have happened.",
    place: "Ahobilam, in the Nandyala district of Andhra Pradesh, is split between the plains village and the forested upper hills — a demanding terrain that has kept mass tourism away and devotion intact.",
    people: "Jeeyars and priests of the Ahobila Mutt, forest-dwelling Chenchu guides, and pilgrims who measure the journey in blisters and blessings.",
    hero: "/assets/projects/ahobilam-hero.jpg",
    poster: "/assets/projects/ahobilam-hero.jpg",
    gallery: ["/assets/projects/ahobilam-2.jpg", "/assets/projects/roots.jpg"],
    credits: [{ role: "Direction & Production", name: "Balcony Originals" }],
    featured: true,
    order: 4,
  },
  {
    slug: "untitled-feature",
    title: "Untitled Feature",
    telugu: "",
    type: "feature",
    status: "in-development",
    categories: ["Feature Film"],
    location: "Rayalaseema",
    district: "",
    state: "Andhra Pradesh",
    country: "India",
    year: "",
    duration: "Feature Film",
    logline: "A story from the soil. Everything else, for now, stays in the soil.",
    synopsis: "Balcony Originals' first feature film is in development — a root-based concept drawn from the land, the people and the moral weather of Rayalaseema. Title, cast and production details will be announced only when approved.",
    story: "The same philosophy that drives our documentaries — rooted stories, authentic people, culture, place, emotion — is being shaped into our first fiction feature.",
    place: "Rayalaseema. Where else.",
    people: "To be announced.",
    hero: "/assets/projects/feature-hero.jpg",
    poster: "/assets/projects/feature-hero.jpg",
    gallery: [],
    credits: [],
    confidential: true,
    featured: true,
    order: 5,
  },
];
